# Generated by Django 5.0.2 on 2024-02-14 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_tags_alter_scope_article_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
