# Generated by Django 5.0.2 on 2024-02-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_article_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="articles",
                through="articles.Scope",
                to="articles.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.article",
                verbose_name="Тематики статьи",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="is_main",
            field=models.BooleanField(verbose_name="Основной"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.tag",
                verbose_name="Раздел",
            ),
        ),
    ]
