# Generated by Django 4.2.6 on 2023-10-19 15:50

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('price', models.PositiveIntegerField()),
                ('release_date', models.DateField(auto_now_add=True)),
                ('lte_exists', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['name'])),
            ],
        ),
    ]
